fix: update more generation and scriptable building

diff --git a/install-filcrypto b/install-filcrypto
--- a/install-filcrypto
+++ b/install-filcrypto
@@ -28,6 +28,7 @@ rust_sources_dir="rust"
 cpu_features_required_for_optimized_release=$(jq -r '.[].check_cpu_for_feature | select(. != null)' < "${rust_sources_dir}/rustc-target-features-optimized.json")
 
 main() {
+    local version=$1
     local __release_flags=$(get_release_flags)
     if [ "${FFI_BUILD_FROM_SOURCE}" != "1" ] && download_release_tarball __tarball_path "${rust_sources_dir}" "filecoin-ffi" "${__release_flags}"; then
         local __tmp_dir=$(mktemp -d)
@@ -41,29 +42,29 @@ main() {
 
         # copy build assets into root of filecoin-ffi
         #
-        find -L "${__tmp_dir}" -type f -name filcrypto.h -exec cp -- "{}" . \;
-        find -L "${__tmp_dir}" -type f -name libfilcrypto.a -exec cp -- "{}" . \;
-        find -L "${__tmp_dir}" -type f -name filcrypto.pc -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name filcrypto-${version}.h -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name libfilcrypto-${version}.a -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name filcrypto-${version}.pc -exec cp -- "{}" . \;
 
-        check_installed_files
+        check_installed_files ${version}
 
-        (>&2 echo "[install-filcrypto/main] successfully installed prebuilt libfilcrypto")
+        (>&2 echo "[install-filcrypto/main] successfully installed prebuilt libfilcrypto-${version}")
     else
-        (>&2 echo "[install-filcrypto/main] building libfilcrypto from local sources (dir = ${rust_sources_dir})")
+        (>&2 echo "[install-filcrypto/main] building libfilcrypto-${version} from local sources (dir = ${rust_sources_dir})")
 
-        # build libfilcrypto (and corresponding header and pkg-config)
+        # build libfilcrypto api version (and corresponding header and pkg-config)
         #
-        build_from_source "filcrypto" "${rust_sources_dir}" "${__release_flags}"
+        build_from_source "${version}" "filcrypto-${version}" "${rust_sources_dir}/api-${version}" "${__release_flags}"
 
         # copy from Rust's build directory (target) to root of filecoin-ffi
         #
-        find -L "${rust_sources_dir}/target/release" -type f -name filcrypto.h -exec cp -- "{}" . \;
-        find -L "${rust_sources_dir}/target/release" -type f -name libfilcrypto.a -exec cp -- "{}" . \;
-        find -L "${rust_sources_dir}" -type f -name filcrypto.pc -exec cp -- "{}" . \;
+        find -L "include" -type f -name filcrypto-${version}.h -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}/target/release" -type f -name libfilcrypto_${version}.a -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}" -type f -name filcrypto-${version}.pc -exec cp -- "{}" . \;
 
-        check_installed_files
+        check_installed_files "${version}"
 
-        (>&2 echo "[install-filcrypto/main] successfully built and installed libfilcrypto from source")
+        (>&2 echo "[install-filcrypto/main] successfully built and installed libfilcrypto-${version} from source")
     fi
 }
 
@@ -125,9 +126,10 @@ download_release_tarball() {
 }
 
 build_from_source() {
-    local __library_name=$1
-    local __rust_sources_path=$2
-    local __release_flags=$3
+    local version=$1
+    local __library_name=$2
+    local __rust_sources_path=$3
+    local __release_flags=$4
     local __repo_sha1=$(git rev-parse HEAD)
     local __repo_sha1_truncated="${__repo_sha1:0:16}"
 
@@ -150,9 +152,9 @@ build_from_source() {
     cargo --version
 
     if [ -n "${__release_flags}" ]; then
-        RUSTFLAGS="-C target-feature=${__release_flags}" ./scripts/build-release.sh "${__library_name}" "$(cat rust-toolchain)"
+        RUSTFLAGS="-C target-feature=${__release_flags}" ../scripts/build-release.sh "${version}" "${__library_name}" "$(cat ../rust-toolchain)"
     else
-        ./scripts/build-release.sh "${__library_name}" "$(cat rust-toolchain)"
+        ../scripts/build-release.sh "${version}" "${__library_name}" "$(cat ../rust-toolchain)"
     fi
 
     popd
@@ -206,20 +208,27 @@ get_release_flags() {
 }
 
 check_installed_files() {
-    if [[ ! -f "./filcrypto.h" ]]; then
-        (>&2 echo "[check_installed_files] failed to install filcrypto.h")
+    local version=$1
+    if [[ ! -f "./filcrypto-${version}.h" ]]; then
+        (>&2 echo "[check_installed_files] failed to install filcrypto-${version}.h")
         exit 1
     fi
 
-    if [[ ! -f "./libfilcrypto.a" ]]; then
-        (>&2 echo "[check_installed_files] failed to install libfilcrypto.a")
+    if [[ ! -f "./libfilcrypto_${version}.a" ]]; then
+        (>&2 echo "[check_installed_files] failed to install libfilcrypto_${version}.a")
         exit 1
     fi
 
-    if [[ ! -f "./filcrypto.pc" ]]; then
-        (>&2 echo "[check_installed_files] failed to install filcrypto.pc")
+    if [[ ! -f "./filcrypto-${version}.pc" ]]; then
+        (>&2 echo "[check_installed_files] failed to install filcrypto-${version}.pc")
         exit 1
     fi
 }
 
-main "$@"; exit
+# API version 1
+main "v1" "$@"
+
+# API version 2
+main "v2" "$@"
+
+exit
