split CPU feature from check + rework script structure
We do runtime feature detection in rust-fil-proofs to determine if your CPU has support for SHA, so we don't need to gate optimized/standard on the processor having SHA support

diff --git a/install-filecoin b/install-filecoin
--- a/install-filecoin
+++ b/install-filecoin
@@ -2,7 +2,72 @@
 
 set -Exeo pipefail
 
-req_cpu_features_optimized=(adx sha sse sse2 avx2 avx sse4.2 sse4.1)
+# set CWD to the root of filecoin-ffi
+#
+cd "$(dirname "${BASH_SOURCE[0]}")"
+
+# tracks where the Rust sources are were we to build locally instead of
+# downloading from GitHub Releases
+#
+rust_sources_dir="rust"
+
+# an array of values passed as 'target-feature' to the Rust compiler if we're
+# building an optimized libfilecoin (which takes advantage of some perf-boosting
+# instruction sets)
+#
+optimized_release_rustc_target_features=($(cat "${rust_sources_dir}/rustc-target-features-optimized.json" | jq -r '.[].rustc_target_feature'))
+
+# each value in this area is checked against the "features" of the hosts CPU
+# in order to determine if the host is suitable for an optimized release
+#
+cpu_features_required_for_optimized_release=($(cat "${rust_sources_dir}/rustc-target-features-optimized.json" | jq -r '.[].check_cpu_for_feature | select(. != null)'))
+
+main() {
+    if [ "${FFI_BUILD_FROM_SOURCE}" != "1" ] && download_release_tarball __tarball_path "${rust_sources_dir}" "filecoin-ffi" $(get_release_type); then
+        __tmp_dir=$(mktemp -d)
+
+        # extract downloaded tarball to temporary directory
+        #
+        tar -C "$__tmp_dir" -xzf "$__tarball_path"
+
+        # copy build assets into root of filecoin-ffi
+        #
+        find -L "${__tmp_dir}" -type f -name filecoin.h -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name libfilecoin.a -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
+
+        (>&2 echo "successfully installed prebuilt libfilecoin")
+    else
+        (>&2 echo "building libfilecoin from local sources (dir = ${rust_sources_dir})")
+
+        # build libfilecoin (and corresponding header and pkg-config)
+        #
+        build_from_source "filecoin" "${rust_sources_dir}" $(get_release_type)
+
+        # copy from Rust's build directory (target) to root of filecoin-ffi
+        #
+        find -L "${rust_sources_dir}/target/release" -type f -name filecoin.h -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}/target/release" -type f -name libfilecoin.a -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
+
+        if [[ ! -f "./filecoin.h" ]]; then
+            (>&2 echo "failed to install filecoin.h")
+            exit 1
+        fi
+
+        if [[ ! -f "./libfilecoin.a" ]]; then
+            (>&2 echo "failed to install libfilecoin.a")
+            exit 1
+        fi
+
+        if [[ ! -f "./filecoin.pc" ]]; then
+            (>&2 echo "failed to install filecoin.pc")
+            exit 1
+        fi
+
+        (>&2 echo "successfully built and installed libfilecoin from source")
+    fi
+}
 
 download_release_tarball() {
     __resultvar=$1
@@ -13,6 +78,7 @@ download_release_tarball() {
     # TODO: This function shouldn't make assumptions about how these releases'
     # names are constructed. Marginally less-bad would be to require that this
     # function's caller provide the release name.
+    #
     __release_name="${__repo_name}-$(uname)-${__release_type}"
     __release_sha1=$(git rev-parse HEAD)
     __release_tag="${__release_sha1:0:16}"
@@ -76,13 +142,14 @@ build_from_source() {
 
     cargo --version
 
-    target_feature=""
-    for x in ${req_cpu_features_optimized[@]}; do
-        target_feature="+${x},${target_feature}"
+    # reduce array of features into the rustc-specific 'target-feature' flag
+    __target_feature=""
+    for x in ${optimized_release_rustc_target_features[@]}; do
+        __target_feature="+${x},${__target_feature}"
     done
 
     if [ "${__release_type}" = "optimized" ]; then
-        RUSTFLAGS="-C target-feature=${target_feature}" ./scripts/build-release.sh $__library_name $(cat rust-toolchain)
+        RUSTFLAGS="-C target-feature=${__target_feature}" ./scripts/build-release.sh $__library_name $(cat rust-toolchain)
     else
         ./scripts/build-release.sh $__library_name $(cat rust-toolchain)
     fi
@@ -91,35 +158,34 @@ build_from_source() {
 }
 
 get_release_type() {
-    searched="cat /proc/cpuinfo | grep flags"
-    features=""
+    __searched="cat /proc/cpuinfo | grep flags"
+    __features=""
 
     # determine where to look for CPU features
     #
     if [[ ! -f "/proc/cpuinfo" ]]; then
         (>&2 echo "No /proc/cpuinfo file; falling back to Darwin feature detection")
-        searched="sysctl -a | grep machdep.cpu | tr '[:upper:]' '[:lower:]' | grep features"
-        features=$(eval "$searched")
+        __searched="sysctl -a | grep machdep.cpu | tr '[:upper:]' '[:lower:]' | grep features"
+        __features=$(eval "$__searched")
     else
-        features=$(cat /proc/cpuinfo | grep flags)
+        __features=$(cat /proc/cpuinfo | grep flags)
     fi
 
     # check for the presence of each required CPU feature
     #
-    optimized=true
-    for x in ${req_cpu_features_optimized[@]}; do
-        if [ "$optimized" = true ]; then
-            y=${x/\./_}
-            if ! [ -z "${features##*$y*}" ]; then
-                (>&2 echo "Your CPU does not support the '${x}' feature (searched '${searched}')")
-                optimized=false
+    __optimized=true
+    for x in ${cpu_features_required_for_optimized_release[@]}; do
+        if [ "$__optimized" = true ]; then
+            if ! [ -z "${__features##*$x*}" ]; then
+                (>&2 echo "Your CPU does not support the '${x}' feature (searched '${__searched}')")
+                __optimized=false
             fi
         fi
     done
 
     # if we couldn't figure out where to look for features, use standard
     #
-    if [ "$optimized" == true ] && ! [ -z "$features" ]; then
+    if [ "$__optimized" == true ] && ! [ -z "$__features" ]; then
         (>&2 echo "Configuring 'optimized' build")
         echo "optimized"
     else
@@ -128,45 +194,4 @@ get_release_type() {
     fi
 }
 
-cd "$(dirname "${BASH_SOURCE[0]}")"
-
-rust_sources_dir="rust"
-
-if [ "${FFI_BUILD_FROM_SOURCE}" != "1" ] && download_release_tarball tarball_path "${rust_sources_dir}" "filecoin-ffi" $(get_release_type); then
-    tmp_dir=$(mktemp -d)
-    tar -C "$tmp_dir" -xzf "$tarball_path"
-
-    find -L "${tmp_dir}" -type f -name filecoin.h -exec cp -- "{}" . \;
-    find -L "${tmp_dir}" -type f -name libfilecoin.a -exec cp -- "{}" . \;
-    find -L "${tmp_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
-
-    (>&2 echo "successfully installed prebuilt libfilecoin")
-else
-    (>&2 echo "building libfilecoin from local sources (dir = ${rust_sources_dir})")
-
-    build_from_source "filecoin" "${rust_sources_dir}" $(get_release_type)
-
-    mkdir -p include
-    mkdir -p lib/pkgconfig
-
-    find -L "${rust_sources_dir}/target/release" -type f -name filecoin.h -exec cp -- "{}" . \;
-    find -L "${rust_sources_dir}/target/release" -type f -name libfilecoin.a -exec cp -- "{}" . \;
-    find -L "${rust_sources_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
-
-    if [[ ! -f "./filecoin.h" ]]; then
-        (>&2 echo "failed to install filecoin.h")
-        exit 1
-    fi
-
-    if [[ ! -f "./libfilecoin.a" ]]; then
-        (>&2 echo "failed to install libfilecoin.a")
-        exit 1
-    fi
-
-    if [[ ! -f "./filecoin.pc" ]]; then
-        (>&2 echo "failed to install filecoin.pc")
-        exit 1
-    fi
-
-    (>&2 echo "successfully built and installed libfilecoin from source")
-fi
+main "$@"; exit
