Chores/rename libfilecoin (#59)
* rename libfilecoin to libfilproofs as per jbenet

* libfilecoin -> libfilcrypto as per jbenet

diff --git a/install-filcrypto b/install-filcrypto
--- a/install-filcrypto
+++ b/install-filcrypto
@@ -13,7 +13,7 @@ cd "$(dirname "${BASH_SOURCE[0]}")"
 rust_sources_dir="rust"
 
 # an array of values passed as 'target-feature' to the Rust compiler if we're
-# building an optimized libfilecoin (which takes advantage of some perf-boosting
+# building an optimized libfilcrypto (which takes advantage of some perf-boosting
 # instruction sets)
 #
 optimized_release_rustc_target_features=$(jq -r '.[].rustc_target_feature' < "${rust_sources_dir}/rustc-target-features-optimized.json")
@@ -36,29 +36,29 @@ main() {
 
         # copy build assets into root of filecoin-ffi
         #
-        find -L "${__tmp_dir}" -type f -name filecoin.h -exec cp -- "{}" . \;
-        find -L "${__tmp_dir}" -type f -name libfilecoin.a -exec cp -- "{}" . \;
-        find -L "${__tmp_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name filcrypto.h -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name libfilcrypto.a -exec cp -- "{}" . \;
+        find -L "${__tmp_dir}" -type f -name filcrypto.pc -exec cp -- "{}" . \;
 
         check_installed_files
 
-        (>&2 echo "[install-filecoin/main] successfully installed prebuilt libfilecoin")
+        (>&2 echo "[install-filcrypto/main] successfully installed prebuilt libfilcrypto")
     else
-        (>&2 echo "[install-filecoin/main] building libfilecoin from local sources (dir = ${rust_sources_dir})")
+        (>&2 echo "[install-filcrypto/main] building libfilcrypto from local sources (dir = ${rust_sources_dir})")
 
-        # build libfilecoin (and corresponding header and pkg-config)
+        # build libfilcrypto (and corresponding header and pkg-config)
         #
-        build_from_source "filecoin" "${rust_sources_dir}" "$(get_release_type)"
+        build_from_source "filcrypto" "${rust_sources_dir}" "$(get_release_type)"
 
         # copy from Rust's build directory (target) to root of filecoin-ffi
         #
-        find -L "${rust_sources_dir}/target/release" -type f -name filecoin.h -exec cp -- "{}" . \;
-        find -L "${rust_sources_dir}/target/release" -type f -name libfilecoin.a -exec cp -- "{}" . \;
-        find -L "${rust_sources_dir}" -type f -name filecoin.pc -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}/target/release" -type f -name filcrypto.h -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}/target/release" -type f -name libfilcrypto.a -exec cp -- "{}" . \;
+        find -L "${rust_sources_dir}" -type f -name filcrypto.pc -exec cp -- "{}" . \;
 
         check_installed_files
 
-        (>&2 echo "[install-filecoin/main] successfully built and installed libfilecoin from source")
+        (>&2 echo "[install-filcrypto/main] successfully built and installed libfilcrypto from source")
     fi
 }
 
@@ -190,18 +190,18 @@ get_release_type() {
 }
 
 check_installed_files() {
-    if [[ ! -f "./filecoin.h" ]]; then
-        (>&2 echo "[check_installed_files] failed to install filecoin.h")
+    if [[ ! -f "./filcrypto.h" ]]; then
+        (>&2 echo "[check_installed_files] failed to install filcrypto.h")
         exit 1
     fi
 
-    if [[ ! -f "./libfilecoin.a" ]]; then
-        (>&2 echo "[check_installed_files] failed to install libfilecoin.a")
+    if [[ ! -f "./libfilcrypto.a" ]]; then
+        (>&2 echo "[check_installed_files] failed to install libfilcrypto.a")
         exit 1
     fi
 
-    if [[ ! -f "./filecoin.pc" ]]; then
-        (>&2 echo "[check_installed_files] failed to install filecoin.pc")
+    if [[ ! -f "./filcrypto.pc" ]]; then
+        (>&2 echo "[check_installed_files] failed to install filcrypto.pc")
         exit 1
     fi
 }
