add functions for pre-committing, committing, staging data, and unsealing (#34)
* refactor(types): move API types into types.rs

* feat(api): stub new API

* feat(write): implement piece writing functions + test

* feat(seal_pre_commit): sector committing and verification + tests

* feat(unseal): allow miner to unseal entire sector

* ci(params): ensure params are installed before running tests

* fix(typo): remove superfluous braces

* fix(nodrop): replace nodrop with ManuallyDrop

* ci(params): ensure params are installed before running tests

* refactor(lazy_static): replace lazy_static with once_cell

* ci(params): ensure params are installed before running tests

* ci(params): ensure params are installed before running tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,11 +1,30 @@
-version: 2
+version: 2.1
 jobs:
+  obtain_parameters:
+    docker:
+      - image: filecoin/rust:latest
+    working_directory: /mnt/crate
+    resource_class: 2xlarge+
+    steps:
+      - configure_env
+      - install_rust
+      - run:
+          name: Install paramcache from head of rust-fil-proofs master branch
+          command: |
+            cargo install filecoin-proofs --bin=paramcache --force --git=https://github.com/filecoin-project/rust-fil-proofs.git --branch=master
+            which paramcache || { printf '%s\n' "missing paramcache binary" >&2; exit 1; }
+      - restore_parameter_cache
+      - run:
+          name: Generate Groth parameters and verifying keys
+          command: paramcache
+      - save_parameter_cache
   cargo_fetch:
     docker:
       - image: filecoin/rust:latest
     working_directory: /mnt/crate
     resource_class: xlarge
     steps:
+      - configure_env
       - checkout
       - restore_cache:
           keys:
@@ -31,8 +50,9 @@ jobs:
     docker:
       - image: filecoin/rust:latest
     working_directory: /mnt/crate
-    resource_class: xlarge
+    resource_class: 2xlarge+
     steps:
+      - configure_env
       - checkout
       - attach_workspace:
           at: "."
@@ -44,7 +64,7 @@ jobs:
             - parameter-cache-{{ .Revision }}
       - run:
           name: Test (nightly)
-          command: cargo test --verbose --all
+          command: cargo test --release --verbose --all
           no_output_timeout: 15m
 
   rustfmt:
@@ -53,6 +73,7 @@ jobs:
     working_directory: /mnt/crate
     resource_class: xlarge
     steps:
+      - configure_env
       - checkout
       - attach_workspace:
           at: "."
@@ -69,6 +90,7 @@ jobs:
     working_directory: /mnt/crate
     resource_class: xlarge
     steps:
+      - configure_env
       - checkout
       - attach_workspace:
           at: "."
@@ -85,6 +107,7 @@ jobs:
     working_directory: /mnt/crate
     resource_class: xlarge
     steps:
+      - configure_env
       - checkout
       - attach_workspace:
           at: "."
@@ -107,6 +130,7 @@ jobs:
     working_directory: ~/crate
     resource_class: large
     steps:
+      - configure_env
       - run:
           name: Configure environment variables
           command: |
@@ -137,6 +161,7 @@ workflows:
   version: 2
   test_all:
     jobs:
+      - obtain_parameters
       - cargo_fetch
       - rustfmt:
           requires:
@@ -146,6 +171,7 @@ workflows:
             - cargo_fetch
       - test:
           requires:
+            - obtain_parameters
             - cargo_fetch
       - build_linux_release:
           requires:
@@ -159,3 +185,31 @@ workflows:
           filters:
             branches:
               only: master
+commands:
+  configure_env:
+    steps:
+      - run:
+          name: Configure environment variables
+          command: |
+            echo 'export RUST_LOG=info' >> $BASH_ENV
+            echo 'export FIL_PROOFS_PARAMETER_CACHE="/tmp/filecoin-parameter-cache"' >> $BASH_ENV
+            echo 'export PATH="${CARGO_HOME}/bin:${PATH}"' >> $BASH_ENV
+            source $BASH_ENV
+  restore_parameter_cache:
+    steps:
+      - restore_cache:
+          key: v15b-proof-params-{{ arch }}
+          paths:
+            - /tmp/filecoin-parameter-cache
+  save_parameter_cache:
+    steps:
+      - save_cache:
+          key: v15b-proof-params-{{ arch }}
+          paths:
+            - /tmp/filecoin-parameter-cache
+  install_rust:
+    steps:
+      - run:
+          name: Install Rust
+          command: |
+            curl https://sh.rustup.rs -sSf | sh -s -- -y
